### ISSUE TITLE
Question about nested transaction (savepoint)

### ISSUE THREAD

**Issue by op13op** [CanopyTax/asyncpgsa#103]
Hello, I'm trying to use nested transaction in pytest fixture to achieve auto rollback in test environment. And I notice asyncpg support savepiont, but I just could not make it.

The following is code snippet:
```python
class ExplilcitRollbackException(Exception):
    pass


@pytest.fixture
async def pg_pool(loop, pg_setting, setup_databse):
    from asyncpgsa import create_pool
    pool = await create_pool(**pg_setting, loop=loop)

    try:
        async with pool.transaction():
            yield pool
            raise ExplilcitRollbackException
    except ExplilcitRollbackException:
        pass
    finally:
        await pool.close()
```

Are there any ways to achieve this, or I could only truncate the table?

**Comment by allburov** [comment]
@op13op have you resolve issue?

If I am not wrong, `pool.transaction` return a context manager with a pair - `connection + transaction`. In above example you have two different connections with two transaction. It's a reason why DB wasn't rollbacked after first test. 

You should create single connection and create two transaction:
```python
pool = await create_pool(**pg_setting, loop=loop)
async with pool.acquire() as con:
    async with con.transaction():
      async with con.transaction():
         yield conn # You MUST use this connection instance in all your code. May be monkeypatch you module or directly pass them. Otherwise you will create new connection without transaction.
```

**Comment by op13op** [comment]
@allburov My apologies for the late reply.
You are right, it's working as expected now.
Thanks a lot.
