### ISSUE TITLE
Incorrect version requirement in 0.27.0 for asyncpg

### ISSUE THREAD

**Issue by ods** [CanopyTax/asyncpgsa#113]
New 0.27.0 version [passes record_class](https://github.com/CanopyTax/asyncpgsa/blob/b9e928ce4a27a2c3964c69cfe5a3189290f1fdaa/asyncpgsa/connection.py#L96) thus being incompatible with asyncpg<0.22.0, but declaration in setup.py [states the opposite](https://github.com/CanopyTax/asyncpgsa/blob/master/setup.py#L13). Probably mistyped `<=` instead of `>=`?

**Comment by nhumrich** [comment]
Very sorry for this. It was indeed a fat finger issue. So sorry it took me so long to respond. Should be fixed in 0.27.1
