### ISSUE TITLE
Missing releases after 0.25 version on github

### ISSUE THREAD

**Issue by alvassin** [CanopyTax/asyncpgsa#115]
Today caught issue with incompatibility asyncpgsa==0.26.1 with asyncpg==0.22.0 (but found that latest release works well!).

So, i opened releases to see the diff between 0.26.1 and latest, but found the latest release described is 0.25. Perhaps, you would like to add other releases to make it easier to see the diffs?

Of course it is possible to build diff against the commits, but releases seem to be little bit faster/easier (and it is bit confusing that you have only part of releases on the github).

**Comment by mixa2130** [comment]
@alvassin actual version is already on github
