### ISSUE TITLE
Use of modulo operator compiles a query unrecognized by asyncpg

### ISSUE THREAD

**Issue by rbcarson** [CanopyTax/asyncpgsa#19]
When a statement that uses the modulo operator is compiled, the default psycopg2 dialect query compiler (`PGCompiler_psycopg2`) used by asyncpgsa has some sort of special treatment of percent signs that results in the compiled query having `%%` instead of `%`, which isn't recognized by asyncpg.

For example, `select([literal_column('10') % 2])`, results in this logged query: `SELECT 10 %% $1 AS anon_1`. This gets rejected by asyncpg: `asyncpg.exceptions.UndefinedFunctionError: operator does not exist: integer %% unknown`.

I noticed that the pypostgresql dialect doesn't deviate from the default query compiler, so I changed connection.py to use that dialect instead. It generates a query with only one `%` as expected, which made asyncpg happy. But I don't know the implications of doing this, and didn't go further than that.

**Comment by nhumrich** [comment]
This is potentially a good fix. If you want to submit a PR I will look into it and try to make sure things aren't broken.

**Comment by nhumrich** [comment]
Fixed in 0.9.0
