### ISSUE TITLE
Suggestion: Update create_pool() for forward compatibility with asyncpg

### ISSUE THREAD

**Issue by achimnol** [CanopyTax/asyncpgsa#30]
Recently **asyncpg** has added new constructor arguments to its `Pool` class, such as `max_inactive_connection_lifetime`.
This has broken my code that uses **asyncpgsa**, not directly **asyncpg**, because `asyncpgsa.Pool` class directly subclasses `asyncpg.Pool` and those new arguments are mandatory.

To remedy such forward-compatibility problems, asyncpg provides [a factory method](https://github.com/MagicStack/asyncpg/blob/f280a5669affbac57cdec252e9c6d4a9e2f956a3/asyncpg/pool.py#L550) which sets default values for newly introduced arguments.

I think it will be nice to have the same factory/wrapper method to create connection pools in **asyncpgsa** as well.

**Comment by achimnol** [comment]
Oh, I just found that **asyncpgsa** already has the proposed factory method. ;)
But still, it has the same problem with the new arguments from underlying **asyncpg**.
Maybe we could just add new arguments following the updates of **asyncpg**, or find some way to automatically adapt to its updates.

**Comment by nhumrich** [comment]
Fixed with #36
