### ISSUE TITLE
Record subscript operator

### ISSUE THREAD

**Issue by skuda** [CanopyTax/asyncpgsa#32]
I am pretty new to SQL Alchemy, this makes me thing I am missing something and that there is a good reason to keep things as they are now so before create a pull request to add this I need to ask:

Why the Record type doesn't handle subscript operator []?

```
row.type_id
1
row['type_id']
Traceback (most recent call last):
  Debug Probe, prompt 53, line 1
builtins.TypeError: 'Record' object is not subscriptable
```

It's pretty easy to add to the record class the method
```
def __getitem__(self, key):
        if isinstance(key, Column):
            key = key.name

        return self.__getattr__(key)
```

So we can do:
```
row.type_id
1
row['type_id']
1
row[models.t_game_server_type.c.type_id]
1
```

Could this create any problem? I would like to be as close as possible to the SQLAlchemy Core syntax.

Thanks!

**Comment by nhumrich** [comment]
Ya. Thats valid. The record object actually has a member, `data` that already acts this way. The record object actually wraps that to provide attributes (dot notation). However, I wouldn't mind the record working both ways. Feel free to add a PR. If you don't I will add this when I get time.

**Comment by skuda** [comment]
Pretty busy today but I will make a PR tomorrow, thanks!
