### ISSUE TITLE
Update to use latest asyncpg

### ISSUE THREAD

**Issue by nhumrich** [CanopyTax/asyncpgsa#33]
Need to update this lib to use the latest version of asyncpg.

**Comment by nhumrich** [comment]
Related Issue: https://github.com/MagicStack/asyncpg/issues/128

**Comment by skuda** [comment]
Do you think you will be able to release this anytime soon? I would really need to use some parameters for asyncpg pool that didn't existed in 0.9.0

Thanks!

**Comment by nhumrich** [comment]
Starting working on this today. Current issue is that the new pool `connection_class` property has some weird bugs and doesn't quite work correctly. I might be filing an issue if I cant figure out a workaround. I will report back here.
If you want more info, asyncpg now uses a "connectionProxy" which at definition time takes the implementation of the connections methods and makes it its own, which means that subclassing and passing in your own connection class is useless, as any methods you "override" never get called since the proxy is going to use its version which is the original methods. So you cant override any "public" methods.

**Comment by skuda** [comment]
Thanks for the info.

Probably talking with asyncpg developers will be a good idea, I think they would be open to make minor changes to make things more easy for asyncpgsa.

**Comment by nhumrich** [comment]
Filed an issue: https://github.com/MagicStack/asyncpg/issues/155

**Comment by carsonyl** [comment]
@nhumrich I happened to grab asyncpgsa 0.12.0 recently, and was happy to get it working in my use case. However, I then hit the same issue that appears to have caused the unit tests to fail and for you to revert it in 0.13.0: the records returned by the Pool are the original `asyncpg.Record`, instead of being wrapped with `asyncpgsa.record.Record`, so `row.column_name` doesn't work.

**Comment by nhumrich** [comment]
Fixed in 0.14.0. Have fun!

**Comment by skuda** [comment]
Awesome, thanks!!
