### ISSUE TITLE
`conn.execute(query)` is not working with params

### ISSUE THREAD

**Issue by visheshell** [CanopyTax/asyncpgsa#41]
From version 0.14.0 `conn.execute()` is not working.

Simple example:
```
async with app.pool.acquire() as conn:
    query = table.update(table.c.some_culumn=123).where(table.c.id=1)
    await conn.execute(query)
```

Will go [asyncpgsa/connection.py](https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/connection.py#L108-L111) :

```

async def execute(self, script, *args, **kwargs) -> str:
        # script, params = compile_query(script, dialect=self._dialect)
        result = await super().execute(script, *args, **kwargs)
        return RecordGenerator(result)

```
And there `*args` will be empty tuple, hence when it would go to `super().execute(script, *args, **kwargs)` which is [`asyncpg.Connection.execute()`](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connection.py#L206-L240) :

```
async def execute(self, query: str, *args, timeout: float=None) -> str:
    ...
    if not args:  # <- WILL ENTER HERE
            return await self._protocol.query(query, timeout)

     _, status, _ = await self._execute(query, args, 0, timeout, True)
    return status.decode()
```

And if i will use version 0.13.0 everything will be alright, because i will pass `*params` and `*args` to `asyncpg.Connection.execute()` and then it will skip `if not args` clause in [`asyncpg.Connectuon.execute`](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connection.py#L236-L237):

```
async def execute(self, script, *args, **kwargs) -> str:
    script, params = compile_query(script, dialect=self._dialect)
    result = await self._connection.execute(script, *params, *args, **kwargs)
    return RecordGenerator(result)
```

I am certainly grateful for that awesome package, and i am willing to help, but i not sure how, because [recent change to omit `compile_query` in `execute` statement](https://github.com/CanopyTax/asyncpgsa/commit/75078a4366c5677098bd4a79306357564318a943#diff-eab523d83da1ac1d08833831dd0113acR108) is made for a reason. And i don't really understand what reason it is.

For a moment i rolled back to 0.13.0 and everything works as expected.

**Comment by nhumrich** [comment]
@visheshell This commit (75078a4366c56770 that you linked) was a bad commit that was a WIP, and shouldn't have been committed. It was rolled back, but probably not correctly.

I think this is a regression. And when I look at tests, they arent passing now. So I am not sure what happened here, but thanks for saying something!

**Comment by nhumrich** [comment]
Ok, I am reminding myself of that change now. Asynpg now calls `_execute` for us on every execution. So the compile_query logic is now there instead of in the individual queries. 

The issue you have mentioned should have already been fixed in 14.2.

Can you try 0.14.2 and let me know if your still having the issue?

**Comment by visheshell** [comment]
@nhumrich i'm sorry for such a delay.

Unfortunately, it's not working because when you pass not compiled query, you pass only one argument.

```
import sqlalchemy as sa

update_query = sa.update(some_table).\
    where(some_table.c.some_col == some_value).\
    values(some_c=some_v)

with pool.acquire() as conn:
    await conn.execute(update_query)
```

Since you pass to `execute()` only `script ` without any `*args` you call `super` method as well without `*args`
```
    async def execute(self, script, *args, **kwargs) -> str:
        # script, params = compile_query(script, dialect=self._dialect)
        result = await super().execute(script, *args, **kwargs)
        return RecordGenerator(result)
```
which will go to [asyncpg/connection.py#L236-L237](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connection.py#L236-L237)

```
if not args:
            return await self._protocol.query(query, timeout)
```
And would raise `TypeError: Expected unicode, got Update`, since query would be not `str/unicode`, but `sqlalchemy.sql.dml.Update`

Why can't we just uncomment [`# script, params = compile_query(script, dialect=self._dialect)` in asyncpgsa.connection.SAConnection.execute()](https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/connection.py#L108-L111) and comment out [`query, compiled_args = compile_query(query, dialect=self._dialect)` in `_execute()`](https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/connection.py#L102-L106) ?

**Comment by nhumrich** [comment]
@visheshell for starters, is there a reason you are trying to use execute here instead of `fetch`?

Second, I made it so execute calls compile_query before `super`. There was an extra check in the super method that made things weird and not work with `_excecute` in all cases.

I added a test for this case, and it is passing in 0.14.2

Thanks for the examples.

**Comment by visheshell** [comment]
@nhumrich i use `execute()` because i make write operations. For reading i successfully use `fetch()` `fetchrow()` and `fetchval()` as it's listed in examples.

With 0.14.2 everything works as expected. Thank you so much! Issue is closed, indeed.
