### ISSUE TITLE
Testing helper doesn't work (SAPool class is gone)

### ISSUE THREAD

**Issue by bitrut** [CanopyTax/asyncpgsa#46]
`ImportError: cannot import name 'SAPool'`
https://github.com/CanopyTax/asyncpgsa/blob/b2cd9b5e3577856c80c292c7c329c05afafb050d/asyncpgsa/testing/mockpool.py#L2
This class is gone now, hence testing helper doesn't work anymore.

**Comment by nhumrich** [comment]
Wow.. How did I miss this... Thank you so much for the report. I will get on this

**Comment by nhumrich** [comment]
Should be fixed in 0.16.0
