### ISSUE TITLE
Incorrect processing of intervals (aka timedelta)

### ISSUE THREAD

**Issue by AmatanHead** [CanopyTax/asyncpgsa#47]
Hello!

So in MagicStack/asyncpg#181 I've reported that there is a bug with processing timedelta instances.

In short, any query that works with intervals fails:

```python
q = sqlalchemy \
    .select([sqlalchemy.func.count()]) \
    .select_from(TASK) \
    .where(sqlalchemy.func.NOW() - TASK.c.last_update > timedelta(seconds=10))

async with app.connection() as c:
    print(await c.fetchval(q))
```

Turns out that this bug happens because [`_dialect`](https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/connection.py#L96) on `SAConnection` is actually `None` when it should be [pypostgresql.dialect()](https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/connection.py#L11). Somehow, `__init__` of the `SAConnection` is commented (see 8c02eb1) and I don't see any reason why. Does anyone know anything about it? Was there any reason to switch to the default dialect?

I'll (try) to send PR to fix this (maybe with some tests added).

**Comment by AmatanHead** [comment]
Ping? Anyone? @nhumrich?

**Comment by nhumrich** [comment]
PR looks good. Thanks for the report. Yet another thing I broke in the update to the new asyncpg. Thanks for the report.

Would you mind adding a test for this so that this doesnt get broken again?
