### ISSUE TITLE
QueryContextManager and query method isolation level is hardcoded

### ISSUE THREAD

**Issue by danigosa** [CanopyTax/asyncpgsa#51]
Here:
https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/pgsingleton.py#L126

Could it be just a `kwarg` argument in `query` and in `QueryContextManager.__init__` methods? `serializable` is not always the desired behavior and in fact overrides `asyncpg` default level (READ COMMITED) silently.

**Comment by nhumrich** [comment]
Yep. I originally wrote the method for read-only queries. But, feel free to make a PR to change the behavior via a kwarg.

**Comment by nhumrich** [comment]
This method has now been removed, due to incorrect usage.
