### ISSUE TITLE
Feature Request: Add optional "echo" or "log" option for queries

### ISSUE THREAD

**Issue by mrasband** [CanopyTax/asyncpgsa#6]
Many libraries provide an optional echoing of their queries, doing this at the library level would reduce the overall boilerplate of needing to do it in the application layer.

This is useful for debugging and general query optimization checking.

**Comment by nhumrich** [comment]
You might find the `connection.compile_query(query, inline=True)` helpful.

**Comment by nhumrich** [comment]
Its possible the `pg.init` method could just accept a `debug` keyword, and debug logs every query.

**Comment by mrasband** [comment]
I'll get on this over the weekend
