### ISSUE TITLE
SyntaxError?

### ISSUE THREAD

**Issue by Hardtack** [CanopyTax/asyncpgsa#64]
`asyncpgsa.transactionmanager.ConnectionTransactionContextManager` raises the `SyntaxError` in if user try to use it with `with ...` not `async with ...`
But it's not syntax error actually. It is right syntax but not right usage!
The error should be the `RuntimeError` as I think.

https://github.com/CanopyTax/asyncpgsa/blob/master/asyncpgsa/transactionmanager.py#L25

**Comment by nhumrich** [comment]
So, looks like aiohttp uses `TypeError` https://github.com/aio-libs/aiohttp/search?utf8=%E2%9C%93&q=__enter__&type=

and aiopg uses a `RuntimeError` https://github.com/aio-libs/aiopg/search?utf8=%E2%9C%93&q=__enter__&type=
