### ISSUE TITLE
Please use minimum version specifier (>=), not compatible specifier (~=)

### ISSUE THREAD

**Issue by Hardtack** [CanopyTax/asyncpgsa#65]
I'm suffering with the bug of _asyncpg_ (https://github.com/MagicStack/asyncpg/issues/158) which is already fixed in _v0.13.0_.

But since asyncpgsa forces to use compatible version of _v0.12.0_, I'm still suffering with the bug.
Please use minimum version specifier in `setup.py` like this

``` python
#!/usr/bin/env python3
from setuptools import setup

setup(
    name='asyncpgsa',
    version=__import__('asyncpgsa').__version__,
    install_requires=[
        'asyncpg >=0.12.0, <1.0',
        'sqlalchemy',
    ],
    packages=['asyncpgsa', 'asyncpgsa.testing'],
    url='https://github.com/canopytax/asyncpgsa',
    license='Apache 2.0',
    author='nhumrich',
    author_email='nick.humrich@canopytax.com',
    description='sqlalchemy support for asyncpg'
)
```

**Comment by nhumrich** [comment]
The problem with this is that asyncpg changes some *significant* backwards incompatible changes sometimes because its not 1.0 yet. So using ~= might actually break you in different ways. I will accept a pr that changes to 0.13.0 if all the tests pass
