### ISSUE TITLE
Dependency on old version of asyncpg

### ISSUE THREAD

**Issue by bitrut** [CanopyTax/asyncpgsa#69]
When using `asyncpgsa` it's hard to use latest version of asyncpg, because there's `asyncpg~=0.12.0` in `install_requires`.
What's more, I'd like to use `asyncpgsa` only as sql query compiler, without using its context managers (as shown [here](http://asyncpgsa.readthedocs.io/en/latest/#compile)). In this case `asyncpg` is not a `asyncpgsa`'s dependency any more in practice. It's just a query compiler.
How about moving `asyncpg` to `extras_require`? Or splitting the library into 2 separate packages (compiler and asyncpg adapter (any better name?)).

**Comment by bitrut** [comment]
@thedrow TBH it just pushes the problem forward in time.

**Comment by nhumrich** [comment]
@bitrut if you modify your requirements txt to have asyncpg as a requirement AFTER asyncpgsa, it should work fine. No one is actually forcing you to use the version waspy expects. But I cant promise it will work on any other version.
