### ISSUE TITLE
Do we need Pool.close()?

### ISSUE THREAD

**Issue by sunghyun-lee** [CanopyTax/asyncpgsa#81]
I'm heavily using `asyncpgsa` in this time, and I came up with one question.

If I want to close all connections from Pool, can I use `Pool.close()` from [asyncpg's Pool method](https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.pool.Pool.close)?

For example, there may be a situation that I want to start and define asyncpgsa singleton object when server starts, and I want to gracefully release Pool connection when server ends.

I will try to add PR with adding this functionality.

**Comment by nhumrich** [comment]
The pool is just an asyncpg pool. So `pool.close()` should already exist. If your using the singleton, you can get the pool using the property `pg.pool`, so `pg.pool.close()` should work.

**Comment by nhumrich** [comment]
Closing, as no response
