### ISSUE TITLE
Using asyncpgsa with alembic in `env.py`

### ISSUE THREAD

**Issue by petedmarsh** [CanopyTax/asyncpgsa#83]
I'm working on a new project and I thought I'd try out `asyncpgsa`. I'm using `alembic` to manage DB migrations, but as I have things set up right now it needs `psycopg2` in order to run - it's not a big problem but I feel a bit silly having both `asyncpgsa` and `psycopg2` in my project as dependencies.

I saw that you mentioned using `alembic` in this issue:

https://github.com/CanopyTax/asyncpgsa/issues/37#issuecomment-316795818

I wondered if you used `alembic` with `asyncpgsa`  and, if so, could you share your `alembic` `env.py`?

**Comment by nhumrich** [comment]
I use pyscopg2 with alembic. It is a little silly... but I do that for now, because migrations don't need to be async.
