### ISSUE TITLE
Typings?

### ISSUE THREAD

**Issue by arusahni** [CanopyTax/asyncpgsa#98]
Hi,

I was wondering if there were/are typings for the library?  I'm trying to reduce the number of mypy exceptions I carve out, and this is one of the ones that mypy yells at me for.

Thanks for the great library!

**Comment by nhumrich** [comment]
I don't use mypy, and as such, not everything is typed. You are welcome to make a PR that type-hints everything if you want.

**Comment by arusahni** [comment]
@nhumrich sounds good. I'll try to carve out some time to work them in.  Thanks for the library!
